#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import time
import std_msgs
import axis
from microscope.msg import microscope_motor, microscope_motor_move, state_microscope_motor, microscope_magnet, state_microscope_magnet

from arom_helper import AromNode



'''
PWM-A
    PWM 0 LED
    PWM 1 BREAK

PWM-B
    PWM 0 XY
    PWM 1 O

##
Osa O - 197 164 st. - mikrokrokovani 1/64
Osa O - 394 328 st. - mikrokrokovani 1/128
'''

class Mikroskop(AromNode):
    node_name = "Mikroskop"
    node_type = "microscope"
    node_pymlab = True

    motor_x_en = True
    motor_y_en = True
    motor_z_en = False
    motor_o_en = True

    def __init__(self, name = "Mikroskop"):

        # Nastaveni ODESILANI ZPRAV z nodu Mikroskop do jinych nodu
        # self.pub_btn = rospy.Publisher('/arom/UI/buttons', std_msgs.msg.String, queue_size=10)
        # self.pub_beep = rospy.Publisher('/beeper/preset', std_msgs.msg.String, queue_size=5)
        self.axis_state = rospy.Publisher('/axis/state', state_microscope_motor, queue_size=5, latch=True)
        self.magnet_state = rospy.Publisher('/magnet/state', state_microscope_magnet, queue_size=5, latch=True)

        # Inicializace sbernice
        AromNode.__init__(self)
        #self.set_feature('sendNum__0',{'addr': "/LED/duty", "name": "LED", 'type': "range", 'min':0, 'max': 100})  #tady se nastaví "feature" pro webove rozhrani (tedy jaky ovladaci prvek se zobrazi)
        #self.set_feature('sendNum__1',{'addr': "/MAG1/duty", "name": "Magnet 1", 'min':-100, 'max': 100})
        #self.set_feature('sendNum__2',{'addr': "/MAG2/duty", "name": "Magnet 2", 'min':-100, 'max': 100})
        #self.set_feature('sendNum__3',{'addr': "/MAG3/duty", "name": "Magnet 3", 'min':-100, 'max': 100})
        
        #Pomocne promenne
        self.led = 0
        self.magnet_polarity = {0: 0b0000, 1: 0b1100, -1: 0b0011}
        self.magnet = {1: 0, 2: 0, 3: 0}
        self.operation = []
        
        # nastaveni jednotek pro pohyb
        # x, y, z - mikrometr; o - 1/10000 otacky
        self.units = {'x': 1, 'y': 1, 'z': 1, 'o': 394328/10000}

        # Co se zobrazi na webu je uvedeno v souboru microscope.feature.hbs
        self.set_feature('external',{'feature': __file__+".feature.hbs"})

        # Nastaveni PRIJMU ZPRAV z uvedenych adres nodu (Subscriber prirazuje fci na konci jako parametr prichozi zpravu, self odkazuje na tuto jednu tridu (Mikroskop))
        rospy.Subscriber("/led/set", std_msgs.msg.String, self.set_led_helper)
        rospy.Subscriber("/MAG1/duty", std_msgs.msg.String, self.magnet1)
        rospy.Subscriber("/MAG2/duty", std_msgs.msg.String, self.magnet2)
        rospy.Subscriber("/MAG3/duty", std_msgs.msg.String, self.magnet3)

        rospy.Subscriber("/magnet/set", microscope_magnet, self.set_magnet_helper)
        rospy.Subscriber("/axis/set", microscope_motor, self.set_motor_helper)
        rospy.Subscriber("/axis/move", microscope_motor_move, self.set_move_helper)

        ##self.pymlab(device="i2cpwm", method="set_ls0", parameters=str(0b11111111))
        #self.pymlab(device="i2cpwmB", method="set_ls1", parameters=str(dict(mode = 0b11111111)))
        #self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 100, duty = 50)))

        # Inicializace HW ovladace HBSTEP01B motorku a HW ovladace I2CPWM01A magnetu
        self.init_motor()
        self.init_mag()

        # Nastaveni casovace (maximalni frekvence opakovani) pro nasledujici smycku
        rate = rospy.Rate(10)
        # jak casto posilat zpravy o stavu (napr na web)
        pub_delay = 0.3 
        last_pub = time.time()
        # Smycka spoustejici poslani zprav o stavu motorku a magnetu
        while not rospy.is_shutdown():
            rate.sleep()

            if len(self.operation)>0:
                print self.operation
                req = self.operation.pop(0)
                print ">>", req
                operation = req['operation']

                if operation == 'set_magnet':
                    self.set_magnet(req['data'])

                elif operation == 'set_motor':
                    self.set_motor(req['data'])

                elif operation == 'set_led':
                    self.set_led(float(req['data'].data))

                elif operation == 'set_move':
                    self.set_move(req['data'])

            if time.time() - last_pub > pub_delay:
                self.send_motor_state()
                self.send_mag_state()

    def set_magnet_helper(self, msg):
        self.operation += [{'operation': 'set_magnet', 'data': msg}]

    def set_magnet(self, msg):
        print("setMagnet", msg)
        if msg.axis == 1:
            if msg.state:
                print("START B0")
                self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b00000100)))
                self.magnet[1] = True
            else:
                print("STOP B0")
                self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b00000011)))
                time.sleep(3)
                self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b00000000)))
                self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                self.magnet[1] = False
                
        elif msg.axis == 2:
            if msg.state:
                print("START B1")
                self.pymlab(device="i2cpwmB", method="set_ls1", parameters=str(dict(mode = 0b00000100)))
                self.magnet[2] = True
            else:
                print("STOP B1")
                self.pymlab(device="i2cpwmB", method="set_ls1", parameters=str(dict(mode = 0b00000011)))
                self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                time.sleep(3)
                self.pymlab(device="i2cpwmB", method="set_ls1", parameters=str(dict(mode = 0b00000000)))
                self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                self.magnet[2] = False

        elif msg.axis == 3:
            if msg.state:
                print("START B2")
                self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b00001100)))
                self.magnet[3] = True
            else:
                print("STOP B2")
                self.pymlab(device="i2cpwmA", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b00000011)))
                time.sleep(3)
                self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b00000000)))
                self.pymlab(device="i2cpwmA", method="set_pwm1", parameters=str(dict(frequency = 150, duty = 100)))
                self.magnet[3] = False



    def set_motor_helper(self, msg):
        self.operation += [{'operation': 'set_motor', 'data': msg}]

    def set_motor(self, msg):
        en = False 

        print("SetMotor", msg)
        if msg.axis == 1 and self.motor_x_en:
            ax = self.motor_x
            en = True
        elif msg.axis == 2 and self.motor_y_en:
            ax = self.motor_y
            en = True
        elif msg.axis == 3 and self.motor_z_en:
            ax = self.motor_z
            en = True
        elif msg.axis == 4 and self.motor_o_en:
            ax = self.motor_o
            en = True
        else:
            print("neznama osa - zastavuji vse!")
            try:
                self.motor_x.Float()
                self.motor_y.Float()
                self.motor_z.Float()
                self.motor_o.Float()
            except Exception as e:
                raise e
            return None

        if en:
            if msg.speed_mode == 0:
                ax.Float()
                print("Zastavuji motor u osy", msg.axis)
            else:
                ax.Run(True, msg.speed_mode)
                print("Spoustim motor u osy", msg.axis)
        return None

    def set_move_helper(self, msg):
        self.operation += [{'operation': 'set_move', 'data': msg}]

    def set_move(self, msg):
        if msg.x != 0 and self.motor_x_en:
            self.motor_x.Move(msg.x*self.units['x'], microsteps = True)
        if msg.y != 0 and self.motor_y_en:
            self.motor_y.Move(msg.y*self.units['y'], microsteps = True)
        if msg.z != 0 and self.motor_z_en:
            self.motor_z.Move(msg.z*self.units['z'], microsteps = True)
        if msg.o != 0 and self.motor_o_en:
            self.motor_o.Move(msg.o*self.units['o'], microsteps = True)

    def init_mag(self):
        self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b00000000)))
        self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b00000000)))
        self.pymlab(device="i2cpwmA", method="set_pwm0", parameters=str(dict(frequency = 200, duty = 50)))
        self.pymlab(device="i2cpwmA", method="set_pwm1", parameters=str(dict(frequency = 200, duty = 50)))

        self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b00000000)))
        self.pymlab(device="i2cpwmB", method="set_ls1", parameters=str(dict(mode = 0b00000000)))
        self.pymlab(device="i2cpwmB", method="set_pwm0", parameters=str(dict(frequency = 200, duty = 50)))
        self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 200, duty = 50)))

        self.led0 = 0
        self.magnet1 = 0
        self.magnet2 = 0
        self.magnet3 = 0


    def set_led_helper(self, msg):
        self.operation += [{'operation': 'set_led', 'data': msg}]
        print(msg)

        
    def set_led(self, duty = 0):
        if duty <= 0:
            print("Off")
            self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b00000001)))
        elif duty >= 100:
            print("FULL")
            self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b00000000)))
        else:
            print("PWM")
            self.pymlab(device="i2cpwmA", method="set_pwm0", parameters=str(dict(frequency = 100, duty = 100-duty)))
            self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b00000010)))


    def callback(self, recive):
        print "led", recive
        self.pymlab(device="i2cpwmB", method="set_pwm1", parameters=str(dict(frequency = 100, duty = 100 - int(recive.data))))


    def send_motor_state(self):
            aray = []

            if self.motor_x_en:
                mx = self.motor_x.getStatus()
                #print(mx)

                a1 = microscope_motor()
                a1.axis = 1
                a1.relative = False
                a1.position = self.mx_pos
                a1.speed_mode = 1
                aray += [a1]

            if self.motor_y_en:
                my = self.motor_y.getStatus()
                #print(my)

                a2 = microscope_motor()
                a2.axis = 2
                a2.relative = False
                a2.position = self.my_pos
                a2.speed_mode = 1
                aray += [a2] 

            if self.motor_z_en:
                mz = self.motor_z.getStatus()
                #print(mz)

                a3 = microscope_motor()
                a3.axis = 3
                a3.relative = False
                a3.position = self.mz_pos
                a3.speed_mode = 1
                aray += [a3]

            if self.motor_o_en:
                mo = self.motor_o.getStatus()
                #print(mo)

                a4 = microscope_motor()
                a4.axis = 4
                a4.relative = False
                a4.position = self.mo_pos
                a4.speed_mode = 1
                aray += [a4]

            self.axis_state.publish(motor=aray)


    def send_mag_state(self):
            aray = []

            a1 = microscope_magnet()
            a1.axis = 1
            a1.state = bool(self.magnet[1])
            aray += [a1]

            a2 = microscope_magnet()
            a2.axis = 2
            a2.state = bool(self.magnet[2])
            aray += [a2] 

            a3 = microscope_magnet()
            a3.axis = 3
            a3.state = bool(self.magnet[3])
            aray += [a3]

            self.magnet_state.publish(magnet=aray)


    def magnet1(self, recive):
        print "magnet1", recive
        if int(recive.data) < 0:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b10000000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmA", method="set_pwm0", parameters=str(dict(frequency = 200, duty = duty)))
            print duty
        else:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmA", method="set_ls0", parameters=str(dict(mode = 0b00100000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmA", method="set_pwm0", parameters=str(dict(frequency = 200, duty = duty)))
            print duty

    def magnet2(self, recive):
        print "magnet2", recive
        if int(recive.data) < 0:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b11000000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmA", method="set_pwm1", parameters=str(dict(frequency = 200, duty = duty)))
            print duty
        else:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmA", method="set_ls1", parameters=str(dict(mode = 0b00110000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmA", method="set_pwm1", parameters=str(dict(frequency = 200, duty = duty)))
            print duty

    def magnet3(self, recive):
        print "magnet3", recive
        if int(recive.data) < 0:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b10000000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmB", method="set_pwm0", parameters=str(dict(frequency = 200, duty = duty)))
            #print duty
        else:
            duty = abs(int(recive.data))
            self.pymlab(device="i2cpwmB", method="set_ls0", parameters=str(dict(mode = 0b00100000)))
            time.sleep(0.1)
            self.pymlab(device="i2cpwmB", method="set_pwm0", parameters=str(dict(frequency = 200, duty = duty)))
            print duty

    def init_motor(self):
        print("Init motor..")
        if self.motor_x_en:
            time.sleep(1.5)
            self.motor_x = axis.axis(SPI = self.pymlab, SPI_CS = 0b0001, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'spi')
            self.motor_x.Setup(
                           MAX_SPEED = 50,
                           KVAL_ACC=0.3,
                           KVAL_RUN=0.3,
                           KVAL_DEC=0.3,
                           ACC = 2,
                           DEC = 2,
                           FS_SPD=3000,
                           STEP_MODE=axis.axis.STEP_MODE_1_128)
            print("Init motor X")
        
        if self.motor_y_en:
            time.sleep(1.5)
            self.motor_y = axis.axis(SPI = self.pymlab, SPI_CS = 0b0010, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'spi')
            self.motor_y.Setup(
                           MAX_SPEED = 60,
                           KVAL_ACC=0.4,
                           KVAL_RUN=0.4,
                           KVAL_DEC=0.4,
                           ACC = 3,
                           DEC = 3, 
                           FS_SPD=3000,
                           STEP_MODE=axis.axis.STEP_MODE_1_128)
            self.motor_y.Run(0, 200)
            print("Init motor Y")
        

        if self.motor_z_en:
            time.sleep(1.5)
            self.motor_z = axis.axis(SPI = self.pymlab, SPI_CS = 0b0100, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'spi')
            self.motor_z.Setup(
                           MAX_SPEED = 500,
                           KVAL_ACC=0.3,
                           KVAL_RUN=0.3,
                           KVAL_DEC=0.3 ,
                           ACC = 100,
                           DEC = 100,
                           FS_SPD=3000,
                           STEP_MODE=axis.axis.STEP_MODE_1_64)
            self.motor_z.Run(1, 200)
            print("Init motor Z")
        

        if self.motor_o_en:
            time.sleep(1.5)
            self.motor_o = axis.axis(SPI = self.pymlab, SPI_CS = 0b1000, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'spi')
            self.motor_o.Setup(
                           MAX_SPEED = 100,
                           KVAL_ACC=0.4,
                           KVAL_RUN=0.2,
                           KVAL_DEC=0.4,
                           ACC = 100,
                           DEC = 100,
                           FS_SPD=3000,
                           STEP_MODE=axis.axis.STEP_MODE_1_128)
            print("Init motor O")
        

        if self.motor_x_en: self.motor_x.Float()
        if self.motor_y_en: self.motor_y.Float()
        if self.motor_z_en: self.motor_z.Float()
        if self.motor_o_en: self.motor_o.Float()

        self.mx_pos = 0
        self.my_pos = 0
        self.mz_pos = 0
        self.mo_pos = 0





if __name__ == '__main__':
    m = Mikroskop()

